Initial commit
alexwti/java-explore-with-me pull request #6
Opened 2023-04-19 21:10 UTC by alexwti

2023-04-20 04:43 UTC, ErkinKasymaliev requested changes
привет, в целом все норм, оставил один коммент.
Но работу пока не принимаю, так как  вкладка чек у вас в PR пустая, такое ощущение что вы удалили случайно нужные файлы. 
Надо добавить их и PR должен пройти все проверки успешно.

2023-04-20 04:43 UTC, ErkinKasymaliev commented on ewm-main/Dockerfile
> +FROM amazoncorretto:17-alpine-jdk
Поставьте версию java в модуле статистики

2023-04-21 10:13 UTC, alexwti commented on ewm-main/Dockerfile
> +FROM amazoncorretto:17-alpine-jdk
Привет!
Да, с чеками очень странно получилось...
Исправил

2023-04-22 10:28 UTC, ErkinKasymaliev commented
привет, сегодня чуть позже к трекеру доступ получу, но работа принята. Если тебе срочно нужно, то закину ее на free work.

2023-04-22 15:09 UTC, ErkinKasymaliev approved these changes
работа принята

2023-04-24 07:03 UTC, merged